import type { QueryResult } from "@/types/semantic.types";
import {
  REVENUE_RUN1,
  REVENUE_RUN2,
  REVENUE_RUN3,
  REVENUE_CORRECT,
} from "./sample-dataset";
import { formatCurrency } from "@/lib/formatters";

/** The main demo query used throughout Module 4 */
export const DEMO_QUERY = "What is total revenue?" as const;

/** Inconsistent run definitions - WITHOUT semantic layer */
export const INCONSISTENT_RUNS: QueryResult[] = [
  {
    queryId: "run-1",
    sql: "SELECT SUM(order_amount)\nFROM orders",
    value: REVENUE_RUN1,
    formattedValue: formatCurrency(REVENUE_RUN1),
    problem:
      "Includes ALL orders regardless of status - cancelled, returned, and pending orders are counted as revenue.",
    isCorrect: false,
  },
  {
    queryId: "run-2",
    sql: "SELECT SUM(order_amount + tax_amount)\nFROM orders\nWHERE status = 'completed'",
    value: REVENUE_RUN2,
    formattedValue: formatCurrency(REVENUE_RUN2),
    problem:
      "Incorrectly adds tax_amount to revenue. Tax is collected on behalf of the government, not company revenue.",
    isCorrect: false,
  },
  {
    queryId: "run-3",
    sql: "SELECT SUM(order_amount - discount)\nFROM orders\nWHERE status != 'cancelled'",
    value: REVENUE_RUN3,
    formattedValue: formatCurrency(REVENUE_RUN3),
    problem:
      "Filters out cancelled orders but still includes returned and pending orders that should not count as realized revenue.",
    isCorrect: false,
  },
];

/** Consistent run definition - WITH semantic layer */
export const CONSISTENT_RUN: QueryResult = {
  queryId: "semantic-run",
  sql: "-- Generated by Semantic Layer\nSELECT SUM(order_amount - discount) AS total_revenue\nFROM orders\nWHERE status = 'completed'",
  value: REVENUE_CORRECT,
  formattedValue: formatCurrency(REVENUE_CORRECT),
  problem: undefined,
  isCorrect: true,
};

/** Labels for the 3 inconsistent agent runs */
export const RUN_LABELS = [
  "Agent Run 1",
  "Agent Run 2",
  "Agent Run 3",
] as const;
